
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cap
    username: cap
    password: password1234@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true